In [40]:

# Import the libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mutual_info_score

In [41]:

# Download and inspect the dataset
url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv"

df = pd.read_csv(url)

print(df.shape)
display(df.head())
print(df.dtypes)
print(df.isnull().sum())

(5000, 9)

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1

lead_source                     str
industry                        str
employment_status               str
location                        str
annual_income               float64
number_of_courses_viewed      int64
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object
lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [42]:

# Handle missing values
categorical = list(df.select_dtypes(include="object").columns)
numerical = list(df.select_dtypes(include="number").columns)

for col in categorical:
    df[col] = df[col].fillna("NA")

for col in numerical:
    df[col] = df[col].fillna(0.0)

print(df.isnull().sum())

lead_source                 0
industry                    0
employment_status           0
location                    0
annual_income               0
number_of_courses_viewed    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

/tmp/ipykernel_4042/3501411926.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical = list(df.select_dtypes(include="object").columns)

In [43]:
# Question 1

print(df["industry"].mode())
print(df["industry"].value_counts())

0    technology
Name: industry, dtype: str
industry
technology       1173
retail            925
healthcare        840
finance           720
education         639
manufacturing     463
NA                240
Name: count, dtype: int64

In [44]:
# Question 2

numerical_features = [
    col for col in numerical if col != "converted"
]

corr = df[numerical_features].corr()
display(corr)

pairs = [
    ("interaction_count", "lead_score"),
    ("number_of_courses_viewed", "lead_score"),
    ("number_of_courses_viewed", "interaction_count"),
    ("annual_income", "interaction_count")
]

for a, b in pairs:
    print(a, "and", b, "=", corr.loc[a, b])

,annual_income,number_of_courses_viewed,interaction_count,lead_score
annual_income,1.000000,0.161300,0.122842,0.229496
number_of_courses_viewed,0.161300,1.000000,0.721609,0.757204
interaction_count,0.122842,0.721609,1.000000,0.915746
lead_score,0.229496,0.757204,0.915746,1.000000

interaction_count and lead_score = 0.9157457980418697
number_of_courses_viewed and lead_score = 0.7572042392104886
number_of_courses_viewed and interaction_count = 0.7216090038937035
annual_income and interaction_count = 0.12284235135955959

In [45]:
# Question 3


from sklearn.model_selection import train_test_split
from sklearn.metrics import mutual_info_score

# Split the dataset into training and test sets
df_full_train, df_test = train_test_split(
    df, test_size=0.2, random_state=42
)

# Split the remaining data into training and validation sets
df_train, df_val = train_test_split(
    df_full_train, test_size=0.25, random_state=42
)

# Store the target values for the training set
y_train = df_train["converted"]

# Select only categorical predictor columns
categorical = [
    col for col in df_train.select_dtypes(
        include=["object", "string"]
    ).columns
    if col != "converted"
]

# Calculate mutual information for each categorical feature
def mutual_info_converted(series):
    return mutual_info_score(series, y_train)

mi = df_train[categorical].apply(mutual_info_converted)

# Sort scores from highest to lowest
mi = mi.sort_values(ascending=False)

print(mi.round(2))

lead_source          0.03
employment_status    0.02
industry             0.00
location             0.00
dtype: float64

In [52]:
# Question 4

# ============================================================
# Machine Learning ZoomCamp 2026
# Homework 3: Classification
# ============================================================

# STEP 1: Import libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, mutual_info_score
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression


# STEP 2: Load the official 2026 dataset
url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv"

df = pd.read_csv(url)

print("Dataset shape:", df.shape)
display(df.head())


# STEP 3: Define categorical and numerical features
# Categorical features represent groups or labels.
# Numerical features represent measurable quantities.

categorical = [
    "lead_source",
    "industry",
    "employment_status",
    "location"
]

numerical = [
    "annual_income",
    "number_of_courses_viewed",
    "interaction_count",
    "lead_score"
]

target = "converted"


# STEP 4: Handle missing values
# Replace missing categorical values with "NA".
# Replace missing numerical values with 0.0.

for col in categorical:
    df[col] = df[col].fillna("NA")

for col in numerical:
    df[col] = df[col].fillna(0.0)

print("\nMissing values after cleaning:")
print(df.isnull().sum())


# ============================================================
# Q1: MODE OF INDUSTRY
# The mode is the most frequently occurring value.
# ============================================================

print("\n========== Q1 ==========")

print("Industry mode:")
print(df["industry"].mode())

print("\nIndustry counts:")
print(df["industry"].value_counts())


# ============================================================
# Q2: BIGGEST CORRELATION
# Correlation measures the strength of a linear relationship.
# ============================================================

print("\n========== Q2 ==========")

corr = df[numerical].corr()
display(corr)

pairs = [
    ("interaction_count", "lead_score"),
    ("number_of_courses_viewed", "lead_score"),
    ("number_of_courses_viewed", "interaction_count"),
    ("annual_income", "interaction_count")
]

for feature1, feature2 in pairs:
    print(
        feature1, "and", feature2, "=",
        corr.loc[feature1, feature2]
    )

best_pair = max(
    pairs,
    key=lambda pair: corr.loc[pair[0], pair[1]]
)

print("Biggest correlation:", best_pair)


# ============================================================
# STEP 5: SPLIT THE DATASET
# 60% training, 20% validation, 20% testing.
# First reserve 20% for testing.
# Then split the remaining 80% into 75% training and 25%
# validation, giving 60% and 20% of the original dataset.
# ============================================================

df_full_train, df_test = train_test_split(
    df,
    test_size=0.2,
    random_state=42
)

df_train, df_val = train_test_split(
    df_full_train,
    test_size=0.25,
    random_state=42
)

# Save the actual answers BEFORE removing the target column.
y_train = df_train[target].values
y_val = df_val[target].values

# Remove the target from the feature data.
# This prevents the model from seeing the correct answers.
df_train = df_train.drop(columns=[target])
df_val = df_val.drop(columns=[target])
df_test = df_test.drop(columns=[target])

print("\nTraining rows:", len(df_train))
print("Validation rows:", len(df_val))
print("Testing rows:", len(df_test))

print("Training labels:", len(y_train))
print("Validation labels:", len(y_val))


# ============================================================
# Q3: BIGGEST MUTUAL INFORMATION
# MI measures how informative a categorical feature is about
# the target converted. Calculate it on training data only.
# ============================================================

print("\n========== Q3 ==========")

def mutual_info_converted(series):
    return mutual_info_score(series, y_train)

mi = df_train[categorical].apply(mutual_info_converted)
mi = mi.sort_values(ascending=False)

print("Mutual information scores:")
print(mi.round(2))

print("Highest MI feature:", mi.idxmax())


# ============================================================
# STEP 6: ENCODE THE FEATURES
# DictVectorizer converts categories into numerical features.
# Dense output avoids the sparse-matrix index error in your
# current environment.
# ============================================================

train_dicts = df_train.to_dict(orient="records")
val_dicts = df_val.to_dict(orient="records")

dv = DictVectorizer(sparse=False)

X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)

print("\nTraining feature matrix:", X_train.shape)
print("Validation feature matrix:", X_val.shape)


# ============================================================
# Q4: TRAIN LOGISTIC REGRESSION
# Train the classifier and measure validation accuracy.
# ============================================================

print("\n========== Q4 ==========")

model = LogisticRegression(
    solver="liblinear",
    C=1.0,
    max_iter=1000,
    random_state=42
)

model.fit(X_train, y_train)

# Predict the validation labels.
y_pred = model.predict(X_val)

# Compare predictions with the actual validation labels.
accuracy = accuracy_score(y_val, y_pred)

print("Validation accuracy:", round(accuracy, 2))


# ============================================================
# Q5: FIND THE LEAST USEFUL FEATURE
# Remove each specified feature individually.
# Compare its accuracy with the baseline accuracy.
# ============================================================

print("\n========== Q5 ==========")

baseline_accuracy = accuracy_score(
    y_val,
    model.predict(X_val)
)

print("Baseline accuracy:", baseline_accuracy)

features_to_remove = [
    "lead_source",
    "number_of_courses_viewed",
    "interaction_count"
]

differences = {}

for feature in features_to_remove:

    # Remove one feature from both datasets.
    train_reduced = df_train.drop(columns=[feature])
    val_reduced = df_val.drop(columns=[feature])

    # Fit a new encoder using the reduced training data.
    dv_reduced = DictVectorizer(sparse=False)

    X_train_reduced = dv_reduced.fit_transform(
        train_reduced.to_dict(orient="records")
    )

    X_val_reduced = dv_reduced.transform(
        val_reduced.to_dict(orient="records")
    )

    # Train the same model with the reduced features.
    model_reduced = LogisticRegression(
        solver="liblinear",
        C=1.0,
        max_iter=1000,
        random_state=42
    )

    model_reduced.fit(X_train_reduced, y_train)

    # Calculate the new accuracy without rounding.
    reduced_accuracy = accuracy_score(
        y_val,
        model_reduced.predict(X_val_reduced)
    )

    # Difference can be positive, zero, or negative.
    difference = baseline_accuracy - reduced_accuracy

    differences[feature] = difference

    print("\nRemoved feature:", feature)
    print("New accuracy:", reduced_accuracy)
    print("Accuracy difference:", difference)

# Choose the feature with the smallest difference.
least_useful = min(differences, key=differences.get)

print("\nFeature with smallest difference:", least_useful)


# ============================================================
# Q6: FIND THE BEST REGULARISATION VALUE C
# Train one model for each required value of C.
# Highest validation accuracy wins.
# If tied, choose the smallest C.
# ============================================================

print("\n========== Q6 ==========")

C_values = [0.000001, 0.00001, 0.0001, 0.001]

C_results = {}

for C in C_values:

    model_c = LogisticRegression(
        solver="liblinear",
        C=C,
        max_iter=1000,
        random_state=42
    )

    model_c.fit(X_train, y_train)

    # Evaluate predictions on the validation set.
    predictions_c = model_c.predict(X_val)

    accuracy_c = accuracy_score(y_val, predictions_c)

    C_results[C] = accuracy_c

    print(
        "C =", C,
        "| Accuracy =", round(accuracy_c, 3)
    )

# Identify the highest accuracy.
best_accuracy = max(C_results.values())

# In case of a tie, select the smallest C.
best_C = min(
    C for C, score in C_results.items()
    if score == best_accuracy
)

print("\nBest C:", best_C)
print("Best accuracy:", round(best_accuracy, 3))


# ============================================================
# FINAL SUMMARY
# Use these results to select the matching homework options.
# ============================================================

print("\n========== FINAL SUMMARY ==========")

print("Q1 - Industry mode:", df["industry"].mode().iloc[0])
print("Q2 - Biggest correlation:", best_pair)
print("Q3 - Highest MI:", mi.idxmax())
print("Q4 - Validation accuracy:", round(accuracy, 2))
print("Q5 - Smallest accuracy difference:", least_useful)
print("Q6 - Best C:", best_C)

Dataset shape: (5000, 9)

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1

Missing values after cleaning:
lead_source                 0
industry                    0
employment_status           0
location                    0
annual_income               0
number_of_courses_viewed    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

========== Q1 ==========
Industry mode:
0    technology
Name: industry, dtype: str

Industry counts:
industry
technology       1173
retail            925
healthcare        840
finance           720
education         639
manufacturing     463
NA                240
Name: count, dtype: int64

========== Q2 ==========

,annual_income,number_of_courses_viewed,interaction_count,lead_score
annual_income,1.000000,0.161300,0.122842,0.229496
number_of_courses_viewed,0.161300,1.000000,0.721609,0.757204
interaction_count,0.122842,0.721609,1.000000,0.915746
lead_score,0.229496,0.757204,0.915746,1.000000

interaction_count and lead_score = 0.9157457980418697
number_of_courses_viewed and lead_score = 0.7572042392104886
number_of_courses_viewed and interaction_count = 0.7216090038937035
annual_income and interaction_count = 0.12284235135955959
Biggest correlation: ('interaction_count', 'lead_score')

Training rows: 3000
Validation rows: 1000
Testing rows: 1000
Training labels: 3000
Validation labels: 1000

========== Q3 ==========
Mutual information scores:
lead_source          0.03
employment_status    0.02
industry             0.00
location             0.00
dtype: float64
Highest MI feature: lead_source

Training feature matrix: (3000, 28)
Validation feature matrix: (1000, 28)

========== Q4 ==========
Validation accuracy: 0.65

========== Q5 ==========
Baseline accuracy: 0.645

Removed feature: lead_source
New accuracy: 0.642
Accuracy difference: 0.0030000000000000027

Removed feature: number_of_courses_viewed
New accuracy: 0.643
Accuracy difference: 0.0020000000000000018

Removed feature: interaction_count
New accuracy: 0.601
Accuracy difference: 0.04400000000000004

Feature with smallest difference: number_of_courses_viewed

========== Q6 ==========
C = 1e-06 | Accuracy = 0.598
C = 1e-05 | Accuracy = 0.598
C = 0.0001 | Accuracy = 0.613
C = 0.001 | Accuracy = 0.645

Best C: 0.001
Best accuracy: 0.645

========== FINAL SUMMARY ==========
Q1 - Industry mode: technology
Q2 - Biggest correlation: ('interaction_count', 'lead_score')
Q3 - Highest MI: lead_source
Q4 - Validation accuracy: 0.65
Q5 - Smallest accuracy difference: number_of_courses_viewed
Q6 - Best C: 0.001

In [48]:

baseline_accuracy = accuracy_score(
    y_val, model.predict(X_val)
)

print("Baseline:", baseline_accuracy)

for feature in [
    "lead_source",
    "number_of_courses_viewed",
    "interaction_count"
]:
    train_reduced = df_train.drop(columns=[feature])
    val_reduced = df_val.drop(columns=[feature])

    dv_reduced = DictVectorizer(sparse=True)

    X_train_reduced = dv_reduced.fit_transform(
        train_reduced.to_dict(orient="records")
    )
    X_val_reduced = dv_reduced.transform(
        val_reduced.to_dict(orient="records")
    )

    model_reduced = LogisticRegression(
        solver="liblinear",
        C=1.0,
        max_iter=1000,
        random_state=42
    )

    model_reduced.fit(X_train_reduced, y_train)

    acc_reduced = accuracy_score(
        y_val, model_reduced.predict(X_val_reduced)
    )

    difference = baseline_accuracy - acc_reduced

    print(
        feature,
        "accuracy:", acc_reduced,
        "difference:", difference
    )

NameError: name 'y_val' is not defined

In [ ]:

baseline_accuracy = accuracy_score(
    y_val, model.predict(X_val)
)

print("Baseline:", baseline_accuracy)

for feature in [
    "lead_source",
    "number_of_courses_viewed",
    "interaction_count"
]:
    train_reduced = df_train.drop(columns=[feature])
    val_reduced = df_val.drop(columns=[feature])

    dv_reduced = DictVectorizer(sparse=True)

    X_train_reduced = dv_reduced.fit_transform(
        train_reduced.to_dict(orient="records")
    )
    X_val_reduced = dv_reduced.transform(
        val_reduced.to_dict(orient="records")
    )

    model_reduced = LogisticRegression(
        solver="liblinear",
        C=1.0,
        max_iter=1000,
        random_state=42
    )

    model_reduced.fit(X_train_reduced, y_train)

    acc_reduced = accuracy_score(
        y_val, model_reduced.predict(X_val_reduced)
    )

    difference = baseline_accuracy - acc_reduced

    print(
        feature,
        "accuracy:", acc_reduced,
        "difference:", difference
    )

NameError: name 'y_val' is not defined

In [47]:

for C in [0.000001, 0.00001, 0.0001, 0.001]:
    model_c = LogisticRegression(
        solver="liblinear",
        C=C,
        max_iter=1000,
        random_state=42
    )

    model_c.fit(X_train, y_train)

    y_pred_c = model_c.predict(X_val)
    acc_c = accuracy_score(y_val, y_pred_c)

    print(C, round(acc_c, 3))

NameError: name 'y_val' is not defined